name: CI/CD Pipiline for DevOps Assignment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "devops/**"
      - "devopsservice/**"
      - "devopscdk/**"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.detect_changes.outputs.repos }}
    steps:
      - name: Checkout devops
        uses: actions/checkout@v4
        with:
          repository: conrose456/devops
          token: ${{ secrets.MY_GH_PAT }}
          path: devops

      - name: Checkout devopsservice
        uses: actions/checkout@v4
        with:
          repository: conrose456/devopsservice
          token: ${{ secrets.MY_GH_PAT }}
          path: devopsservice

      - name: Checkout devopscdk
        uses: actions/checkout@v4
        with:
          repository: conrose456/devopscdk
          token: ${{ secrets.MY_GH_PAT }}
          path: devopscdk

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd devops && npm install
          cd devopsservice && npm install
          cd devopscdk && npm install

      - name: Build repositories
        run: |
          for repo in devops devopsservice devopscdk; do
            echo "Building $repo"
            cd $repo && npm run build
          done

      - name: Commit build atrifacts
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Build modified repos" || echo "No Changes to commit"
          git push
