name: CI/CD Pipiline for DevOps Assignment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "devops/**"
      - "devopsservice/**"
      - "devopscdk/**"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.detect_changes.outputs.repos }}
    steps:
      - name: Checkout devops
        uses: actions/checkout@v4
        with:
          repository: ConRose456/SE-DevOps
          token: ${{ secrets.MY_GH_PAT }}
          path: devops

      - name: Checkout devopsservice
        uses: actions/checkout@v4
        with:
          repository: ConRose456/SE-DevOpsService
          token: ${{ secrets.MY_GH_PAT }}
          path: devopsservice

      - name: Checkout devopscdk
        uses: actions/checkout@v4
        with:
          repository: ConRose456/SE-DevOpsCDK
          token: ${{ secrets.MY_GH_PAT }}
          path: devopscdk

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Configure npm to use GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_GH_PAT }}" > devopscdk/.npmrc
          echo "@conrose456:registry=https://npm.pkg.github.com/" >> ~/.npmrc

      - name: Install dependencies
        run: |
          cd devops && npm install
          cd ../devopsservice && npm install
          cd ../devopscdk && npm install

      - name: Build repositories
        run: |
          for repo in devops devopsservice devopscdk; do
            echo "Building $repo"
            ls
            cd $repo && npm run build
            ls
          done

      - name: Commit build atrifacts
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Build modified repos" || echo "No Changes to commit"
          git push
